title: 编程语言
email: hanjianwei@zjgsu.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
    编程语言的历史及特点
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pl.zjgsu.xyz"

twitter_username: hanjianwei
github_username:  zjgsu-pl

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed

show_downloads: true
github:
  zip_url: /assets/programming.pdf
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
